In [1]:
import tensorflow as tf

In [2]:
?tf.contrib.learn

In [3]:
g = tf.Graph()
with g.as_default():
    a = 3
    b = 5
    x = tf.add(a, b)
with tf.Session(graph=g) as sess:
    print(sess.run(x))

8


In [4]:
tf.get_default_graph()

In [7]:
a = tf.constant(2, name='a')
b = tf.constant(3, name='b')
c = tf.add(a, b, name='c')
with tf.Session() as sess:
    writer = tf.summary.FileWriter('./graphs', sess.graph)
    print(sess.run(c))
writer.close()

5


In [8]:
a = tf.constant([2, 2], name="a")
b = tf.constant([[0, 1], [2, 3]], name="b")
x = tf.add(a, b, name='add')
y = tf.multiply(a, b, name='mul')
with tf.Session() as sess:
    x, y = sess.run([x, y])
    print(x, y)

[[2 3]
 [4 5]] [[0 2]
 [4 6]]


In [11]:
print(tf.zeros(shape=(2, 3), dtype=tf.int32))

Tensor("zeros_2:0", shape=(2, 3), dtype=int32)


In [12]:
tf.zeros_like(x)

<tf.Tensor 'zeros_like:0' shape=(2, 2) dtype=int32>

In [15]:
a = tf.fill([2, 3], 7)
b = tf.fill([2, 3], 5)
c = tf.add(a, b)
with tf.Session() as sess:
    print(sess.run(c))

[[12 12 12]
 [12 12 12]]


In [20]:
ls = tf.lin_space(start=5.0, stop=10.0, num=10, name='ls')
with tf.Session() as sess:
    print(sess.run(ls))

[  5.           5.55555534   6.11111116   6.66666698   7.22222233
   7.77777767   8.33333397   8.88888931   9.44444466  10.        ]


In [22]:
r = tf.range(start=5, limit=15, delta=3, name='r')
with tf.Session() as sess:
    print(sess.run(r))

[ 5  8 11 14]


In [23]:
t_0 = 19
temp1 = tf.zeros_like(t_0)
temp2 = tf.ones_like(t_0)
with tf.Session() as sess:
    print(sess.run([temp1, temp2]))

[0, 1]


In [32]:
t_1 = ['apple', 'peach', 'banana']
temp1 = tf.zeros_like(t_1)
# temp2 = tf.ones_like(t_1)
with tf.Session() as sess:
    print(sess.run([temp1]))

[array([b'', b'', b''], dtype=object)]


In [27]:
t_2 = [[True, False, False],
 [False, False, True],
 [False, True, False]] 
temp1 = tf.zeros_like(t_2)
temp2 = tf.ones_like(t_2)
with tf.Session() as sess:
    print(sess.run([temp1, temp2]))

[array([[False, False, False],
       [False, False, False],
       [False, False, False]], dtype=bool), array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)]


In [38]:
x = tf.Variable(3)
x.initializer
x.value()
x.assign(9)

with tf.Session() as sess:
    sess.run(x)

FailedPreconditionError: Attempting to use uninitialized value Variable_5
	 [[Node: _retval_Variable_5_0_0 = _Retval[T=DT_INT32, index=0, _device="/job:localhost/replica:0/task:0/cpu:0"](Variable_5)]]

In [39]:
x = tf.range(5)
with tf.Session() as sess:
    y = sess.run(x)
    for i in y:
        print(i)

0
1
2
3
4


In [42]:
x = tf.string("jjj")
with tf.Session() as sess:
    print(sess.run(x))

TypeError: 'DType' object is not callable

In [43]:
my_const = tf.constant([1.0, 2.0], name="my_const")
print(tf.get_default_graph().as_graph_def())

node {
  name: "Const"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 2
      }
    }
  }
}
node {
  name: "Const_1"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 3
      }
    }
  }
}
node {
  name: "Const_2"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 2
      }
    }
  }
}
node {
  name: "Const_3"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_v

In [53]:
W = tf.Variable(tf.zeros([784,10]))
with tf.Session() as sess:
    sess.run(W.initializer)
    print(sess.run(W))

[[ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]]


In [54]:
W = tf.Variable(tf.zeros([784,10]))
with tf.Session() as sess:
    sess.run(W.initializer)
    print(W.eval())

[[ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]]


In [60]:
W = tf.Variable(tf.zeros([784,10]))
W_assign = W.assign(tf.fill([784, 10], 9.0))
with tf.Session() as sess:
    sess.run(W_assign)
    print(W.eval())

[[ 9.  9.  9. ...,  9.  9.  9.]
 [ 9.  9.  9. ...,  9.  9.  9.]
 [ 9.  9.  9. ...,  9.  9.  9.]
 ..., 
 [ 9.  9.  9. ...,  9.  9.  9.]
 [ 9.  9.  9. ...,  9.  9.  9.]
 [ 9.  9.  9. ...,  9.  9.  9.]]


In [63]:
x1 = tf.Variable(9)
sess1 = tf.Session()
sess2 = tf.Session()
x1_assign1 = x1.assign_add(3)
x1_assign2 = x1.assign_sub(5)

sess1.run(x1.initializer)
sess2.run(x1.initializer)

print(sess1.run(x1_assign1))
print(sess2.run(x1_assign2))

sess1.close()
sess2.close()

12
4


In [77]:
W = tf.Variable(tf.truncated_normal([700, 10]))
U = tf.Variable(W * 2)
with tf.Session() as sess:
    sess.run(W.initializer)
    sess.run(U.initializer)
    print(sess.run(W))
    print(sess.run(U))

[[-0.59411758  0.09068252 -0.03671884 ...,  0.20283359 -0.98994452
   1.10706377]
 [ 0.13278636 -0.92001379  0.10593828 ..., -0.55047899  0.19025308
  -0.73603511]
 [-1.5225544   0.85702896 -0.51545286 ...,  0.29156849 -0.67399949
   1.55139184]
 ..., 
 [-0.06630341 -1.6490829   1.07749593 ...,  0.94684267 -0.94386882
  -1.39427996]
 [ 1.08064544 -0.4552829  -1.19285834 ..., -0.46919319 -0.14255294
  -0.31822157]
 [ 0.05792568  0.20968735  1.75449896 ...,  0.78456551  1.43926489
  -0.13058929]]
[[-1.18823516  0.18136504 -0.07343768 ...,  0.40566719 -1.97988904
   2.21412754]
 [ 0.26557273 -1.84002757  0.21187656 ..., -1.10095799  0.38050616
  -1.47207022]
 [-3.0451088   1.71405792 -1.03090572 ...,  0.58313698 -1.34799898
   3.10278368]
 ..., 
 [-0.13260682 -3.2981658   2.15499187 ...,  1.89368534 -1.88773763
  -2.78855991]
 [ 2.16129088 -0.91056579 -2.38571668 ..., -0.93838638 -0.28510588
  -0.63644314]
 [ 0.11585136  0.4193747   3.50899792 ...,  1.56913102  2.87852979
  -0.26117858]]


In [79]:
sess = tf.InteractiveSession()
a = tf.constant(3)
b = tf.constant(5)
c = tf.add(a, b)
print(c.eval())
sess.close()

8


In [2]:
x = tf.Variable(10, name='x')
y = tf.Variable(20, name='y')
z = tf.add(x, y)

with tf.Session() as sess:
	sess.run(tf.global_variables_initializer())
	writer = tf.summary.FileWriter('./graphs/l2', sess.graph)
	for _ in range(10):
		sess.run(z)
	print(tf.get_default_graph().as_graph_def())
	writer.close()

node {
  name: "x/initial_value"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 10
      }
    }
  }
}
node {
  name: "x"
  op: "VariableV2"
  attr {
    key: "container"
    value {
      s: ""
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
      }
    }
  }
  attr {
    key: "shared_name"
    value {
      s: ""
    }
  }
}
node {
  name: "x/Assign"
  op: "Assign"
  input: "x"
  input: "x/initial_value"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@x"
      }
    }
  }
  attr {
    key: "use_locking"
    value {
      b: true
    }
  }
  attr {
    key: "validate_shape"
    value {
      b: true
    }
  }
}
node {
  name: "x/read"
  op: "Identity"
  input

In [ ]:
x = tf.Variable(10, name='x')
y = tf.Variable(20, name='y')

with tf.Session() as sess:
	sess.run(tf.global_variables_initializer())
	writer = tf.summary.FileWriter('./graphs/l2', sess.graph)
	for _ in range(10):
		sess.run(tf.add(x, y))
	print(tf.get_default_graph().as_graph_def()) 
	writer.close()